### ISSUE TITLE
Build fail on CentOS7

### ISSUE THREAD

**Issue by hbxfwjww** [flexVDI/cerbero#1]
Build fail on CentOS7, the command:
./cerbero-uninstalled -c config/cross-android-armv7.cbc bootstrap

The last error message:
WARNING: Could not recover status
Recipe does not support platform: linux Exiting

**Comment by fireforge1982** [comment]
I have met the same error, i clone the project and execute follow cmd:
./cerbero-uninstalled -c config/cross-android-armv7.cbc bootstrap

The last error message:
File /home/bdh/cerbero/android-ndk-r10e/android-ndk-r10e-linux-x86_64.bin already downloaded.
WARNING: Using default configuration because /home/bdh/.cerbero/cerbero.cbc is missing
WARNING: Could not recover status
Recipe does not support platform: linux Exiting

I build this with fedora 23 , 64bit pc, python 2.7.11

**Comment by SoerenBusse** [comment]
Same issue. Any fix?

**Comment by slp** [comment]
Sorry, but currently we only support building the libraries under macOS 10.11, mainly because we use it for generating both Android and iOS versions at the same time.
